// Generated register defines for chimera_padframe_aon_config

// Copyright information found in source file:
// Copyright 2020 ETH Zurich and University of Bologna.

// Licensing information found in source file:
// Licensed under Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51

#ifndef _CHIMERA_PADFRAME_AON_CONFIG_REG_DEFS_
#define _CHIMERA_PADFRAME_AON_CONFIG_REG_DEFS_

#ifdef __cplusplus
extern "C" {
#endif
// Register width
#define CHIMERA_PADFRAME_AON_CONFIG_PARAM_REG_WIDTH 32

// Read-only IP Information register
#define CHIMERA_PADFRAME_AON_CONFIG_INFO_REG_OFFSET 0x0
#define CHIMERA_PADFRAME_AON_CONFIG_INFO_HW_VERSION_MASK 0xffff
#define CHIMERA_PADFRAME_AON_CONFIG_INFO_HW_VERSION_OFFSET 0
#define CHIMERA_PADFRAME_AON_CONFIG_INFO_HW_VERSION_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_INFO_HW_VERSION_MASK, \
                          .index = CHIMERA_PADFRAME_AON_CONFIG_INFO_HW_VERSION_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_INFO_PADCOUNT_MASK 0xffff
#define CHIMERA_PADFRAME_AON_CONFIG_INFO_PADCOUNT_OFFSET 16
#define CHIMERA_PADFRAME_AON_CONFIG_INFO_PADCOUNT_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_INFO_PADCOUNT_MASK, \
                          .index = CHIMERA_PADFRAME_AON_CONFIG_INFO_PADCOUNT_OFFSET})

// Pad signal configuration.
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_CFG_REG_OFFSET 0x4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_CFG_CHIP2PAD_BIT 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_CFG_DRV_MASK 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_CFG_DRV_OFFSET 1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_CFG_DRV_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_CFG_DRV_MASK, \
                          .index = CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_CFG_DRV_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_CFG_PDE_BIT 3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_CFG_PUE_BIT 4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_CFG_RXE_BIT 5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_CFG_SLW_BIT 6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_CFG_SMT_BIT 7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_CFG_TRIE_BIT 8

// Pad signal port multiplex selection for pad gpio_0. The programmed value
// defines which port
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_MUX_SEL_REG_OFFSET 0x8
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_MUX_SEL_GPIO_0_MUX_SEL_MASK 0xf
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_MUX_SEL_GPIO_0_MUX_SEL_OFFSET 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_MUX_SEL_GPIO_0_MUX_SEL_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_MUX_SEL_GPIO_0_MUX_SEL_MASK, \
                          .index = \
                              CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_MUX_SEL_GPIO_0_MUX_SEL_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_MUX_SEL_GPIO_0_MUX_SEL_VALUE_REGISTER 0x0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_MUX_SEL_GPIO_0_MUX_SEL_VALUE_PORT_GPIOA_GPIO0 0x1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_MUX_SEL_GPIO_0_MUX_SEL_VALUE_PORT_I2C0_SCL 0x2
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_MUX_SEL_GPIO_0_MUX_SEL_VALUE_PORT_I2C0_SDA 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_MUX_SEL_GPIO_0_MUX_SEL_VALUE_PORT_QSPI0_CSB0 0x4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_MUX_SEL_GPIO_0_MUX_SEL_VALUE_PORT_QSPI0_CSB1 0x5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_MUX_SEL_GPIO_0_MUX_SEL_VALUE_PORT_QSPI0_SCK 0x6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_MUX_SEL_GPIO_0_MUX_SEL_VALUE_PORT_QSPI0_SD0 0x7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_MUX_SEL_GPIO_0_MUX_SEL_VALUE_PORT_QSPI0_SD1 0x8
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_MUX_SEL_GPIO_0_MUX_SEL_VALUE_PORT_QSPI0_SD2 0x9
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_MUX_SEL_GPIO_0_MUX_SEL_VALUE_PORT_QSPI0_SD3 0xa
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_MUX_SEL_GPIO_0_MUX_SEL_VALUE_PORT_UART0_RX 0xb
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_0_MUX_SEL_GPIO_0_MUX_SEL_VALUE_PORT_UART0_TX 0xc

// Pad signal configuration.
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_CFG_REG_OFFSET 0xc
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_CFG_CHIP2PAD_BIT 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_CFG_DRV_MASK 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_CFG_DRV_OFFSET 1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_CFG_DRV_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_CFG_DRV_MASK, \
                          .index = CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_CFG_DRV_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_CFG_PDE_BIT 3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_CFG_PUE_BIT 4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_CFG_RXE_BIT 5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_CFG_SLW_BIT 6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_CFG_SMT_BIT 7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_CFG_TRIE_BIT 8

// Pad signal port multiplex selection for pad gpio_1. The programmed value
// defines which port
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_MUX_SEL_REG_OFFSET 0x10
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_MUX_SEL_GPIO_1_MUX_SEL_MASK 0xf
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_MUX_SEL_GPIO_1_MUX_SEL_OFFSET 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_MUX_SEL_GPIO_1_MUX_SEL_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_MUX_SEL_GPIO_1_MUX_SEL_MASK, \
                          .index = \
                              CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_MUX_SEL_GPIO_1_MUX_SEL_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_MUX_SEL_GPIO_1_MUX_SEL_VALUE_REGISTER 0x0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_MUX_SEL_GPIO_1_MUX_SEL_VALUE_PORT_GPIOA_GPIO1 0x1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_MUX_SEL_GPIO_1_MUX_SEL_VALUE_PORT_I2C0_SCL 0x2
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_MUX_SEL_GPIO_1_MUX_SEL_VALUE_PORT_I2C0_SDA 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_MUX_SEL_GPIO_1_MUX_SEL_VALUE_PORT_QSPI0_CSB0 0x4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_MUX_SEL_GPIO_1_MUX_SEL_VALUE_PORT_QSPI0_CSB1 0x5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_MUX_SEL_GPIO_1_MUX_SEL_VALUE_PORT_QSPI0_SCK 0x6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_MUX_SEL_GPIO_1_MUX_SEL_VALUE_PORT_QSPI0_SD0 0x7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_MUX_SEL_GPIO_1_MUX_SEL_VALUE_PORT_QSPI0_SD1 0x8
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_MUX_SEL_GPIO_1_MUX_SEL_VALUE_PORT_QSPI0_SD2 0x9
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_MUX_SEL_GPIO_1_MUX_SEL_VALUE_PORT_QSPI0_SD3 0xa
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_MUX_SEL_GPIO_1_MUX_SEL_VALUE_PORT_UART0_RX 0xb
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_1_MUX_SEL_GPIO_1_MUX_SEL_VALUE_PORT_UART0_TX 0xc

// Pad signal configuration.
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_CFG_REG_OFFSET 0x14
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_CFG_CHIP2PAD_BIT 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_CFG_DRV_MASK 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_CFG_DRV_OFFSET 1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_CFG_DRV_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_CFG_DRV_MASK, \
                          .index = CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_CFG_DRV_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_CFG_PDE_BIT 3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_CFG_PUE_BIT 4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_CFG_RXE_BIT 5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_CFG_SLW_BIT 6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_CFG_SMT_BIT 7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_CFG_TRIE_BIT 8

// Pad signal port multiplex selection for pad gpio_2. The programmed value
// defines which port
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_MUX_SEL_REG_OFFSET 0x18
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_MUX_SEL_GPIO_2_MUX_SEL_MASK 0xf
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_MUX_SEL_GPIO_2_MUX_SEL_OFFSET 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_MUX_SEL_GPIO_2_MUX_SEL_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_MUX_SEL_GPIO_2_MUX_SEL_MASK, \
                          .index = \
                              CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_MUX_SEL_GPIO_2_MUX_SEL_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_MUX_SEL_GPIO_2_MUX_SEL_VALUE_REGISTER 0x0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_MUX_SEL_GPIO_2_MUX_SEL_VALUE_PORT_GPIOA_GPIO2 0x1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_MUX_SEL_GPIO_2_MUX_SEL_VALUE_PORT_I2C0_SCL 0x2
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_MUX_SEL_GPIO_2_MUX_SEL_VALUE_PORT_I2C0_SDA 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_MUX_SEL_GPIO_2_MUX_SEL_VALUE_PORT_QSPI0_CSB0 0x4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_MUX_SEL_GPIO_2_MUX_SEL_VALUE_PORT_QSPI0_CSB1 0x5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_MUX_SEL_GPIO_2_MUX_SEL_VALUE_PORT_QSPI0_SCK 0x6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_MUX_SEL_GPIO_2_MUX_SEL_VALUE_PORT_QSPI0_SD0 0x7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_MUX_SEL_GPIO_2_MUX_SEL_VALUE_PORT_QSPI0_SD1 0x8
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_MUX_SEL_GPIO_2_MUX_SEL_VALUE_PORT_QSPI0_SD2 0x9
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_MUX_SEL_GPIO_2_MUX_SEL_VALUE_PORT_QSPI0_SD3 0xa
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_MUX_SEL_GPIO_2_MUX_SEL_VALUE_PORT_UART0_RX 0xb
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_2_MUX_SEL_GPIO_2_MUX_SEL_VALUE_PORT_UART0_TX 0xc

// Pad signal configuration.
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_CFG_REG_OFFSET 0x1c
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_CFG_CHIP2PAD_BIT 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_CFG_DRV_MASK 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_CFG_DRV_OFFSET 1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_CFG_DRV_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_CFG_DRV_MASK, \
                          .index = CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_CFG_DRV_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_CFG_PDE_BIT 3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_CFG_PUE_BIT 4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_CFG_RXE_BIT 5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_CFG_SLW_BIT 6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_CFG_SMT_BIT 7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_CFG_TRIE_BIT 8

// Pad signal port multiplex selection for pad gpio_3. The programmed value
// defines which port
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_MUX_SEL_REG_OFFSET 0x20
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_MUX_SEL_GPIO_3_MUX_SEL_MASK 0xf
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_MUX_SEL_GPIO_3_MUX_SEL_OFFSET 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_MUX_SEL_GPIO_3_MUX_SEL_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_MUX_SEL_GPIO_3_MUX_SEL_MASK, \
                          .index = \
                              CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_MUX_SEL_GPIO_3_MUX_SEL_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_MUX_SEL_GPIO_3_MUX_SEL_VALUE_REGISTER 0x0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_MUX_SEL_GPIO_3_MUX_SEL_VALUE_PORT_GPIOA_GPIO3 0x1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_MUX_SEL_GPIO_3_MUX_SEL_VALUE_PORT_I2C0_SCL 0x2
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_MUX_SEL_GPIO_3_MUX_SEL_VALUE_PORT_I2C0_SDA 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_MUX_SEL_GPIO_3_MUX_SEL_VALUE_PORT_QSPI0_CSB0 0x4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_MUX_SEL_GPIO_3_MUX_SEL_VALUE_PORT_QSPI0_CSB1 0x5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_MUX_SEL_GPIO_3_MUX_SEL_VALUE_PORT_QSPI0_SCK 0x6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_MUX_SEL_GPIO_3_MUX_SEL_VALUE_PORT_QSPI0_SD0 0x7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_MUX_SEL_GPIO_3_MUX_SEL_VALUE_PORT_QSPI0_SD1 0x8
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_MUX_SEL_GPIO_3_MUX_SEL_VALUE_PORT_QSPI0_SD2 0x9
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_MUX_SEL_GPIO_3_MUX_SEL_VALUE_PORT_QSPI0_SD3 0xa
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_MUX_SEL_GPIO_3_MUX_SEL_VALUE_PORT_UART0_RX 0xb
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_3_MUX_SEL_GPIO_3_MUX_SEL_VALUE_PORT_UART0_TX 0xc

// Pad signal configuration.
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_CFG_REG_OFFSET 0x24
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_CFG_CHIP2PAD_BIT 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_CFG_DRV_MASK 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_CFG_DRV_OFFSET 1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_CFG_DRV_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_CFG_DRV_MASK, \
                          .index = CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_CFG_DRV_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_CFG_PDE_BIT 3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_CFG_PUE_BIT 4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_CFG_RXE_BIT 5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_CFG_SLW_BIT 6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_CFG_SMT_BIT 7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_CFG_TRIE_BIT 8

// Pad signal port multiplex selection for pad gpio_4. The programmed value
// defines which port
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_MUX_SEL_REG_OFFSET 0x28
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_MUX_SEL_GPIO_4_MUX_SEL_MASK 0xf
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_MUX_SEL_GPIO_4_MUX_SEL_OFFSET 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_MUX_SEL_GPIO_4_MUX_SEL_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_MUX_SEL_GPIO_4_MUX_SEL_MASK, \
                          .index = \
                              CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_MUX_SEL_GPIO_4_MUX_SEL_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_MUX_SEL_GPIO_4_MUX_SEL_VALUE_REGISTER 0x0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_MUX_SEL_GPIO_4_MUX_SEL_VALUE_PORT_GPIOA_GPIO4 0x1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_MUX_SEL_GPIO_4_MUX_SEL_VALUE_PORT_I2C0_SCL 0x2
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_MUX_SEL_GPIO_4_MUX_SEL_VALUE_PORT_I2C0_SDA 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_MUX_SEL_GPIO_4_MUX_SEL_VALUE_PORT_QSPI0_CSB0 0x4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_MUX_SEL_GPIO_4_MUX_SEL_VALUE_PORT_QSPI0_CSB1 0x5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_MUX_SEL_GPIO_4_MUX_SEL_VALUE_PORT_QSPI0_SCK 0x6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_MUX_SEL_GPIO_4_MUX_SEL_VALUE_PORT_QSPI0_SD0 0x7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_MUX_SEL_GPIO_4_MUX_SEL_VALUE_PORT_QSPI0_SD1 0x8
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_MUX_SEL_GPIO_4_MUX_SEL_VALUE_PORT_QSPI0_SD2 0x9
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_MUX_SEL_GPIO_4_MUX_SEL_VALUE_PORT_QSPI0_SD3 0xa
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_MUX_SEL_GPIO_4_MUX_SEL_VALUE_PORT_UART0_RX 0xb
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_4_MUX_SEL_GPIO_4_MUX_SEL_VALUE_PORT_UART0_TX 0xc

// Pad signal configuration.
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_CFG_REG_OFFSET 0x2c
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_CFG_CHIP2PAD_BIT 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_CFG_DRV_MASK 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_CFG_DRV_OFFSET 1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_CFG_DRV_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_CFG_DRV_MASK, \
                          .index = CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_CFG_DRV_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_CFG_PDE_BIT 3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_CFG_PUE_BIT 4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_CFG_RXE_BIT 5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_CFG_SLW_BIT 6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_CFG_SMT_BIT 7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_CFG_TRIE_BIT 8

// Pad signal port multiplex selection for pad gpio_5. The programmed value
// defines which port
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_MUX_SEL_REG_OFFSET 0x30
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_MUX_SEL_GPIO_5_MUX_SEL_MASK 0xf
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_MUX_SEL_GPIO_5_MUX_SEL_OFFSET 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_MUX_SEL_GPIO_5_MUX_SEL_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_MUX_SEL_GPIO_5_MUX_SEL_MASK, \
                          .index = \
                              CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_MUX_SEL_GPIO_5_MUX_SEL_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_MUX_SEL_GPIO_5_MUX_SEL_VALUE_REGISTER 0x0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_MUX_SEL_GPIO_5_MUX_SEL_VALUE_PORT_GPIOA_GPIO5 0x1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_MUX_SEL_GPIO_5_MUX_SEL_VALUE_PORT_I2C0_SCL 0x2
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_MUX_SEL_GPIO_5_MUX_SEL_VALUE_PORT_I2C0_SDA 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_MUX_SEL_GPIO_5_MUX_SEL_VALUE_PORT_QSPI0_CSB0 0x4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_MUX_SEL_GPIO_5_MUX_SEL_VALUE_PORT_QSPI0_CSB1 0x5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_MUX_SEL_GPIO_5_MUX_SEL_VALUE_PORT_QSPI0_SCK 0x6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_MUX_SEL_GPIO_5_MUX_SEL_VALUE_PORT_QSPI0_SD0 0x7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_MUX_SEL_GPIO_5_MUX_SEL_VALUE_PORT_QSPI0_SD1 0x8
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_MUX_SEL_GPIO_5_MUX_SEL_VALUE_PORT_QSPI0_SD2 0x9
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_MUX_SEL_GPIO_5_MUX_SEL_VALUE_PORT_QSPI0_SD3 0xa
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_MUX_SEL_GPIO_5_MUX_SEL_VALUE_PORT_UART0_RX 0xb
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_5_MUX_SEL_GPIO_5_MUX_SEL_VALUE_PORT_UART0_TX 0xc

// Pad signal configuration.
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_CFG_REG_OFFSET 0x34
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_CFG_CHIP2PAD_BIT 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_CFG_DRV_MASK 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_CFG_DRV_OFFSET 1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_CFG_DRV_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_CFG_DRV_MASK, \
                          .index = CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_CFG_DRV_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_CFG_PDE_BIT 3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_CFG_PUE_BIT 4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_CFG_RXE_BIT 5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_CFG_SLW_BIT 6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_CFG_SMT_BIT 7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_CFG_TRIE_BIT 8

// Pad signal port multiplex selection for pad gpio_6. The programmed value
// defines which port
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_MUX_SEL_REG_OFFSET 0x38
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_MUX_SEL_GPIO_6_MUX_SEL_MASK 0xf
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_MUX_SEL_GPIO_6_MUX_SEL_OFFSET 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_MUX_SEL_GPIO_6_MUX_SEL_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_MUX_SEL_GPIO_6_MUX_SEL_MASK, \
                          .index = \
                              CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_MUX_SEL_GPIO_6_MUX_SEL_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_MUX_SEL_GPIO_6_MUX_SEL_VALUE_REGISTER 0x0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_MUX_SEL_GPIO_6_MUX_SEL_VALUE_PORT_GPIOA_GPIO6 0x1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_MUX_SEL_GPIO_6_MUX_SEL_VALUE_PORT_I2C0_SCL 0x2
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_MUX_SEL_GPIO_6_MUX_SEL_VALUE_PORT_I2C0_SDA 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_MUX_SEL_GPIO_6_MUX_SEL_VALUE_PORT_QSPI0_CSB0 0x4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_MUX_SEL_GPIO_6_MUX_SEL_VALUE_PORT_QSPI0_CSB1 0x5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_MUX_SEL_GPIO_6_MUX_SEL_VALUE_PORT_QSPI0_SCK 0x6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_MUX_SEL_GPIO_6_MUX_SEL_VALUE_PORT_QSPI0_SD0 0x7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_MUX_SEL_GPIO_6_MUX_SEL_VALUE_PORT_QSPI0_SD1 0x8
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_MUX_SEL_GPIO_6_MUX_SEL_VALUE_PORT_QSPI0_SD2 0x9
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_MUX_SEL_GPIO_6_MUX_SEL_VALUE_PORT_QSPI0_SD3 0xa
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_MUX_SEL_GPIO_6_MUX_SEL_VALUE_PORT_UART0_RX 0xb
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_6_MUX_SEL_GPIO_6_MUX_SEL_VALUE_PORT_UART0_TX 0xc

// Pad signal configuration.
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_CFG_REG_OFFSET 0x3c
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_CFG_CHIP2PAD_BIT 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_CFG_DRV_MASK 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_CFG_DRV_OFFSET 1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_CFG_DRV_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_CFG_DRV_MASK, \
                          .index = CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_CFG_DRV_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_CFG_PDE_BIT 3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_CFG_PUE_BIT 4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_CFG_RXE_BIT 5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_CFG_SLW_BIT 6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_CFG_SMT_BIT 7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_CFG_TRIE_BIT 8

// Pad signal port multiplex selection for pad gpio_7. The programmed value
// defines which port
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_MUX_SEL_REG_OFFSET 0x40
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_MUX_SEL_GPIO_7_MUX_SEL_MASK 0xf
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_MUX_SEL_GPIO_7_MUX_SEL_OFFSET 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_MUX_SEL_GPIO_7_MUX_SEL_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_MUX_SEL_GPIO_7_MUX_SEL_MASK, \
                          .index = \
                              CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_MUX_SEL_GPIO_7_MUX_SEL_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_MUX_SEL_GPIO_7_MUX_SEL_VALUE_REGISTER 0x0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_MUX_SEL_GPIO_7_MUX_SEL_VALUE_PORT_GPIOA_GPIO7 0x1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_MUX_SEL_GPIO_7_MUX_SEL_VALUE_PORT_I2C0_SCL 0x2
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_MUX_SEL_GPIO_7_MUX_SEL_VALUE_PORT_I2C0_SDA 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_MUX_SEL_GPIO_7_MUX_SEL_VALUE_PORT_QSPI0_CSB0 0x4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_MUX_SEL_GPIO_7_MUX_SEL_VALUE_PORT_QSPI0_CSB1 0x5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_MUX_SEL_GPIO_7_MUX_SEL_VALUE_PORT_QSPI0_SCK 0x6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_MUX_SEL_GPIO_7_MUX_SEL_VALUE_PORT_QSPI0_SD0 0x7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_MUX_SEL_GPIO_7_MUX_SEL_VALUE_PORT_QSPI0_SD1 0x8
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_MUX_SEL_GPIO_7_MUX_SEL_VALUE_PORT_QSPI0_SD2 0x9
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_MUX_SEL_GPIO_7_MUX_SEL_VALUE_PORT_QSPI0_SD3 0xa
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_MUX_SEL_GPIO_7_MUX_SEL_VALUE_PORT_UART0_RX 0xb
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_7_MUX_SEL_GPIO_7_MUX_SEL_VALUE_PORT_UART0_TX 0xc

// Pad signal configuration.
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_CFG_REG_OFFSET 0x44
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_CFG_CHIP2PAD_BIT 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_CFG_DRV_MASK 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_CFG_DRV_OFFSET 1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_CFG_DRV_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_CFG_DRV_MASK, \
                          .index = CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_CFG_DRV_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_CFG_PDE_BIT 3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_CFG_PUE_BIT 4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_CFG_RXE_BIT 5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_CFG_SLW_BIT 6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_CFG_SMT_BIT 7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_CFG_TRIE_BIT 8

// Pad signal port multiplex selection for pad gpio_8. The programmed value
// defines which port
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_MUX_SEL_REG_OFFSET 0x48
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_MUX_SEL_GPIO_8_MUX_SEL_MASK 0xf
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_MUX_SEL_GPIO_8_MUX_SEL_OFFSET 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_MUX_SEL_GPIO_8_MUX_SEL_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_MUX_SEL_GPIO_8_MUX_SEL_MASK, \
                          .index = \
                              CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_MUX_SEL_GPIO_8_MUX_SEL_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_MUX_SEL_GPIO_8_MUX_SEL_VALUE_REGISTER 0x0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_MUX_SEL_GPIO_8_MUX_SEL_VALUE_PORT_GPIOA_GPIO8 0x1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_MUX_SEL_GPIO_8_MUX_SEL_VALUE_PORT_I2C0_SCL 0x2
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_MUX_SEL_GPIO_8_MUX_SEL_VALUE_PORT_I2C0_SDA 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_MUX_SEL_GPIO_8_MUX_SEL_VALUE_PORT_QSPI0_CSB0 0x4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_MUX_SEL_GPIO_8_MUX_SEL_VALUE_PORT_QSPI0_CSB1 0x5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_MUX_SEL_GPIO_8_MUX_SEL_VALUE_PORT_QSPI0_SCK 0x6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_MUX_SEL_GPIO_8_MUX_SEL_VALUE_PORT_QSPI0_SD0 0x7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_MUX_SEL_GPIO_8_MUX_SEL_VALUE_PORT_QSPI0_SD1 0x8
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_MUX_SEL_GPIO_8_MUX_SEL_VALUE_PORT_QSPI0_SD2 0x9
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_MUX_SEL_GPIO_8_MUX_SEL_VALUE_PORT_QSPI0_SD3 0xa
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_MUX_SEL_GPIO_8_MUX_SEL_VALUE_PORT_UART0_RX 0xb
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_8_MUX_SEL_GPIO_8_MUX_SEL_VALUE_PORT_UART0_TX 0xc

// Pad signal configuration.
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_CFG_REG_OFFSET 0x4c
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_CFG_CHIP2PAD_BIT 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_CFG_DRV_MASK 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_CFG_DRV_OFFSET 1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_CFG_DRV_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_CFG_DRV_MASK, \
                          .index = CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_CFG_DRV_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_CFG_PDE_BIT 3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_CFG_PUE_BIT 4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_CFG_RXE_BIT 5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_CFG_SLW_BIT 6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_CFG_SMT_BIT 7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_CFG_TRIE_BIT 8

// Pad signal port multiplex selection for pad gpio_9. The programmed value
// defines which port
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_MUX_SEL_REG_OFFSET 0x50
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_MUX_SEL_GPIO_9_MUX_SEL_MASK 0xf
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_MUX_SEL_GPIO_9_MUX_SEL_OFFSET 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_MUX_SEL_GPIO_9_MUX_SEL_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_MUX_SEL_GPIO_9_MUX_SEL_MASK, \
                          .index = \
                              CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_MUX_SEL_GPIO_9_MUX_SEL_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_MUX_SEL_GPIO_9_MUX_SEL_VALUE_REGISTER 0x0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_MUX_SEL_GPIO_9_MUX_SEL_VALUE_PORT_GPIOA_GPIO9 0x1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_MUX_SEL_GPIO_9_MUX_SEL_VALUE_PORT_I2C0_SCL 0x2
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_MUX_SEL_GPIO_9_MUX_SEL_VALUE_PORT_I2C0_SDA 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_MUX_SEL_GPIO_9_MUX_SEL_VALUE_PORT_QSPI0_CSB0 0x4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_MUX_SEL_GPIO_9_MUX_SEL_VALUE_PORT_QSPI0_CSB1 0x5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_MUX_SEL_GPIO_9_MUX_SEL_VALUE_PORT_QSPI0_SCK 0x6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_MUX_SEL_GPIO_9_MUX_SEL_VALUE_PORT_QSPI0_SD0 0x7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_MUX_SEL_GPIO_9_MUX_SEL_VALUE_PORT_QSPI0_SD1 0x8
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_MUX_SEL_GPIO_9_MUX_SEL_VALUE_PORT_QSPI0_SD2 0x9
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_MUX_SEL_GPIO_9_MUX_SEL_VALUE_PORT_QSPI0_SD3 0xa
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_MUX_SEL_GPIO_9_MUX_SEL_VALUE_PORT_UART0_RX 0xb
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_9_MUX_SEL_GPIO_9_MUX_SEL_VALUE_PORT_UART0_TX 0xc

// Pad signal configuration.
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_CFG_REG_OFFSET 0x54
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_CFG_CHIP2PAD_BIT 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_CFG_DRV_MASK 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_CFG_DRV_OFFSET 1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_CFG_DRV_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_CFG_DRV_MASK, \
                          .index = CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_CFG_DRV_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_CFG_PDE_BIT 3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_CFG_PUE_BIT 4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_CFG_RXE_BIT 5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_CFG_SLW_BIT 6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_CFG_SMT_BIT 7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_CFG_TRIE_BIT 8

// Pad signal port multiplex selection for pad gpio_10. The programmed value
// defines which port
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_MUX_SEL_REG_OFFSET 0x58
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_MUX_SEL_GPIO_10_MUX_SEL_MASK 0xf
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_MUX_SEL_GPIO_10_MUX_SEL_OFFSET 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_MUX_SEL_GPIO_10_MUX_SEL_FIELD \
    ((bitfield_field32_t){ \
        .mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_MUX_SEL_GPIO_10_MUX_SEL_MASK, \
        .index = CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_MUX_SEL_GPIO_10_MUX_SEL_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_MUX_SEL_GPIO_10_MUX_SEL_VALUE_REGISTER 0x0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_MUX_SEL_GPIO_10_MUX_SEL_VALUE_PORT_GPIOA_GPIO10 0x1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_MUX_SEL_GPIO_10_MUX_SEL_VALUE_PORT_I2C0_SCL 0x2
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_MUX_SEL_GPIO_10_MUX_SEL_VALUE_PORT_I2C0_SDA 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_MUX_SEL_GPIO_10_MUX_SEL_VALUE_PORT_QSPI0_CSB0 0x4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_MUX_SEL_GPIO_10_MUX_SEL_VALUE_PORT_QSPI0_CSB1 0x5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_MUX_SEL_GPIO_10_MUX_SEL_VALUE_PORT_QSPI0_SCK 0x6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_MUX_SEL_GPIO_10_MUX_SEL_VALUE_PORT_QSPI0_SD0 0x7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_MUX_SEL_GPIO_10_MUX_SEL_VALUE_PORT_QSPI0_SD1 0x8
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_MUX_SEL_GPIO_10_MUX_SEL_VALUE_PORT_QSPI0_SD2 0x9
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_MUX_SEL_GPIO_10_MUX_SEL_VALUE_PORT_QSPI0_SD3 0xa
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_MUX_SEL_GPIO_10_MUX_SEL_VALUE_PORT_UART0_RX 0xb
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_10_MUX_SEL_GPIO_10_MUX_SEL_VALUE_PORT_UART0_TX 0xc

// Pad signal configuration.
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_CFG_REG_OFFSET 0x5c
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_CFG_CHIP2PAD_BIT 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_CFG_DRV_MASK 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_CFG_DRV_OFFSET 1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_CFG_DRV_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_CFG_DRV_MASK, \
                          .index = CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_CFG_DRV_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_CFG_PDE_BIT 3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_CFG_PUE_BIT 4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_CFG_RXE_BIT 5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_CFG_SLW_BIT 6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_CFG_SMT_BIT 7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_CFG_TRIE_BIT 8

// Pad signal port multiplex selection for pad gpio_11. The programmed value
// defines which port
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_MUX_SEL_REG_OFFSET 0x60
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_MUX_SEL_GPIO_11_MUX_SEL_MASK 0xf
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_MUX_SEL_GPIO_11_MUX_SEL_OFFSET 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_MUX_SEL_GPIO_11_MUX_SEL_FIELD \
    ((bitfield_field32_t){ \
        .mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_MUX_SEL_GPIO_11_MUX_SEL_MASK, \
        .index = CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_MUX_SEL_GPIO_11_MUX_SEL_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_MUX_SEL_GPIO_11_MUX_SEL_VALUE_REGISTER 0x0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_MUX_SEL_GPIO_11_MUX_SEL_VALUE_PORT_GPIOA_GPIO11 0x1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_MUX_SEL_GPIO_11_MUX_SEL_VALUE_PORT_I2C0_SCL 0x2
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_MUX_SEL_GPIO_11_MUX_SEL_VALUE_PORT_I2C0_SDA 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_MUX_SEL_GPIO_11_MUX_SEL_VALUE_PORT_QSPI0_CSB0 0x4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_MUX_SEL_GPIO_11_MUX_SEL_VALUE_PORT_QSPI0_CSB1 0x5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_MUX_SEL_GPIO_11_MUX_SEL_VALUE_PORT_QSPI0_SCK 0x6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_MUX_SEL_GPIO_11_MUX_SEL_VALUE_PORT_QSPI0_SD0 0x7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_MUX_SEL_GPIO_11_MUX_SEL_VALUE_PORT_QSPI0_SD1 0x8
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_MUX_SEL_GPIO_11_MUX_SEL_VALUE_PORT_QSPI0_SD2 0x9
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_MUX_SEL_GPIO_11_MUX_SEL_VALUE_PORT_QSPI0_SD3 0xa
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_MUX_SEL_GPIO_11_MUX_SEL_VALUE_PORT_UART0_RX 0xb
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_11_MUX_SEL_GPIO_11_MUX_SEL_VALUE_PORT_UART0_TX 0xc

// Pad signal configuration.
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_CFG_REG_OFFSET 0x64
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_CFG_CHIP2PAD_BIT 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_CFG_DRV_MASK 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_CFG_DRV_OFFSET 1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_CFG_DRV_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_CFG_DRV_MASK, \
                          .index = CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_CFG_DRV_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_CFG_PDE_BIT 3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_CFG_PUE_BIT 4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_CFG_RXE_BIT 5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_CFG_SLW_BIT 6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_CFG_SMT_BIT 7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_CFG_TRIE_BIT 8

// Pad signal port multiplex selection for pad gpio_12. The programmed value
// defines which port
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_MUX_SEL_REG_OFFSET 0x68
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_MUX_SEL_GPIO_12_MUX_SEL_MASK 0xf
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_MUX_SEL_GPIO_12_MUX_SEL_OFFSET 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_MUX_SEL_GPIO_12_MUX_SEL_FIELD \
    ((bitfield_field32_t){ \
        .mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_MUX_SEL_GPIO_12_MUX_SEL_MASK, \
        .index = CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_MUX_SEL_GPIO_12_MUX_SEL_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_MUX_SEL_GPIO_12_MUX_SEL_VALUE_REGISTER 0x0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_MUX_SEL_GPIO_12_MUX_SEL_VALUE_PORT_GPIOA_GPIO12 0x1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_MUX_SEL_GPIO_12_MUX_SEL_VALUE_PORT_I2C0_SCL 0x2
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_MUX_SEL_GPIO_12_MUX_SEL_VALUE_PORT_I2C0_SDA 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_MUX_SEL_GPIO_12_MUX_SEL_VALUE_PORT_QSPI0_CSB0 0x4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_MUX_SEL_GPIO_12_MUX_SEL_VALUE_PORT_QSPI0_CSB1 0x5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_MUX_SEL_GPIO_12_MUX_SEL_VALUE_PORT_QSPI0_SCK 0x6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_MUX_SEL_GPIO_12_MUX_SEL_VALUE_PORT_QSPI0_SD0 0x7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_MUX_SEL_GPIO_12_MUX_SEL_VALUE_PORT_QSPI0_SD1 0x8
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_MUX_SEL_GPIO_12_MUX_SEL_VALUE_PORT_QSPI0_SD2 0x9
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_MUX_SEL_GPIO_12_MUX_SEL_VALUE_PORT_QSPI0_SD3 0xa
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_MUX_SEL_GPIO_12_MUX_SEL_VALUE_PORT_UART0_RX 0xb
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_12_MUX_SEL_GPIO_12_MUX_SEL_VALUE_PORT_UART0_TX 0xc

// Pad signal configuration.
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_CFG_REG_OFFSET 0x6c
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_CFG_CHIP2PAD_BIT 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_CFG_DRV_MASK 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_CFG_DRV_OFFSET 1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_CFG_DRV_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_CFG_DRV_MASK, \
                          .index = CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_CFG_DRV_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_CFG_PDE_BIT 3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_CFG_PUE_BIT 4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_CFG_RXE_BIT 5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_CFG_SLW_BIT 6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_CFG_SMT_BIT 7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_CFG_TRIE_BIT 8

// Pad signal port multiplex selection for pad gpio_13. The programmed value
// defines which port
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_MUX_SEL_REG_OFFSET 0x70
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_MUX_SEL_GPIO_13_MUX_SEL_MASK 0xf
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_MUX_SEL_GPIO_13_MUX_SEL_OFFSET 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_MUX_SEL_GPIO_13_MUX_SEL_FIELD \
    ((bitfield_field32_t){ \
        .mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_MUX_SEL_GPIO_13_MUX_SEL_MASK, \
        .index = CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_MUX_SEL_GPIO_13_MUX_SEL_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_MUX_SEL_GPIO_13_MUX_SEL_VALUE_REGISTER 0x0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_MUX_SEL_GPIO_13_MUX_SEL_VALUE_PORT_GPIOA_GPIO13 0x1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_MUX_SEL_GPIO_13_MUX_SEL_VALUE_PORT_I2C0_SCL 0x2
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_MUX_SEL_GPIO_13_MUX_SEL_VALUE_PORT_I2C0_SDA 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_MUX_SEL_GPIO_13_MUX_SEL_VALUE_PORT_QSPI0_CSB0 0x4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_MUX_SEL_GPIO_13_MUX_SEL_VALUE_PORT_QSPI0_CSB1 0x5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_MUX_SEL_GPIO_13_MUX_SEL_VALUE_PORT_QSPI0_SCK 0x6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_MUX_SEL_GPIO_13_MUX_SEL_VALUE_PORT_QSPI0_SD0 0x7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_MUX_SEL_GPIO_13_MUX_SEL_VALUE_PORT_QSPI0_SD1 0x8
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_MUX_SEL_GPIO_13_MUX_SEL_VALUE_PORT_QSPI0_SD2 0x9
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_MUX_SEL_GPIO_13_MUX_SEL_VALUE_PORT_QSPI0_SD3 0xa
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_MUX_SEL_GPIO_13_MUX_SEL_VALUE_PORT_UART0_RX 0xb
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_13_MUX_SEL_GPIO_13_MUX_SEL_VALUE_PORT_UART0_TX 0xc

// Pad signal configuration.
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_CFG_REG_OFFSET 0x74
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_CFG_CHIP2PAD_BIT 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_CFG_DRV_MASK 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_CFG_DRV_OFFSET 1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_CFG_DRV_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_CFG_DRV_MASK, \
                          .index = CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_CFG_DRV_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_CFG_PDE_BIT 3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_CFG_PUE_BIT 4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_CFG_RXE_BIT 5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_CFG_SLW_BIT 6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_CFG_SMT_BIT 7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_CFG_TRIE_BIT 8

// Pad signal port multiplex selection for pad gpio_14. The programmed value
// defines which port
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_MUX_SEL_REG_OFFSET 0x78
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_MUX_SEL_GPIO_14_MUX_SEL_MASK 0xf
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_MUX_SEL_GPIO_14_MUX_SEL_OFFSET 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_MUX_SEL_GPIO_14_MUX_SEL_FIELD \
    ((bitfield_field32_t){ \
        .mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_MUX_SEL_GPIO_14_MUX_SEL_MASK, \
        .index = CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_MUX_SEL_GPIO_14_MUX_SEL_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_MUX_SEL_GPIO_14_MUX_SEL_VALUE_REGISTER 0x0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_MUX_SEL_GPIO_14_MUX_SEL_VALUE_PORT_GPIOA_GPIO14 0x1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_MUX_SEL_GPIO_14_MUX_SEL_VALUE_PORT_I2C0_SCL 0x2
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_MUX_SEL_GPIO_14_MUX_SEL_VALUE_PORT_I2C0_SDA 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_MUX_SEL_GPIO_14_MUX_SEL_VALUE_PORT_QSPI0_CSB0 0x4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_MUX_SEL_GPIO_14_MUX_SEL_VALUE_PORT_QSPI0_CSB1 0x5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_MUX_SEL_GPIO_14_MUX_SEL_VALUE_PORT_QSPI0_SCK 0x6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_MUX_SEL_GPIO_14_MUX_SEL_VALUE_PORT_QSPI0_SD0 0x7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_MUX_SEL_GPIO_14_MUX_SEL_VALUE_PORT_QSPI0_SD1 0x8
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_MUX_SEL_GPIO_14_MUX_SEL_VALUE_PORT_QSPI0_SD2 0x9
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_MUX_SEL_GPIO_14_MUX_SEL_VALUE_PORT_QSPI0_SD3 0xa
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_MUX_SEL_GPIO_14_MUX_SEL_VALUE_PORT_UART0_RX 0xb
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_14_MUX_SEL_GPIO_14_MUX_SEL_VALUE_PORT_UART0_TX 0xc

// Pad signal configuration.
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_CFG_REG_OFFSET 0x7c
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_CFG_CHIP2PAD_BIT 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_CFG_DRV_MASK 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_CFG_DRV_OFFSET 1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_CFG_DRV_FIELD \
    ((bitfield_field32_t){.mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_CFG_DRV_MASK, \
                          .index = CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_CFG_DRV_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_CFG_PDE_BIT 3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_CFG_PUE_BIT 4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_CFG_RXE_BIT 5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_CFG_SLW_BIT 6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_CFG_SMT_BIT 7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_CFG_TRIE_BIT 8

// Pad signal port multiplex selection for pad gpio_15. The programmed value
// defines which port
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_MUX_SEL_REG_OFFSET 0x80
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_MUX_SEL_GPIO_15_MUX_SEL_MASK 0xf
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_MUX_SEL_GPIO_15_MUX_SEL_OFFSET 0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_MUX_SEL_GPIO_15_MUX_SEL_FIELD \
    ((bitfield_field32_t){ \
        .mask = CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_MUX_SEL_GPIO_15_MUX_SEL_MASK, \
        .index = CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_MUX_SEL_GPIO_15_MUX_SEL_OFFSET})
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_MUX_SEL_GPIO_15_MUX_SEL_VALUE_REGISTER 0x0
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_MUX_SEL_GPIO_15_MUX_SEL_VALUE_PORT_GPIOA_GPIO15 0x1
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_MUX_SEL_GPIO_15_MUX_SEL_VALUE_PORT_I2C0_SCL 0x2
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_MUX_SEL_GPIO_15_MUX_SEL_VALUE_PORT_I2C0_SDA 0x3
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_MUX_SEL_GPIO_15_MUX_SEL_VALUE_PORT_QSPI0_CSB0 0x4
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_MUX_SEL_GPIO_15_MUX_SEL_VALUE_PORT_QSPI0_CSB1 0x5
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_MUX_SEL_GPIO_15_MUX_SEL_VALUE_PORT_QSPI0_SCK 0x6
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_MUX_SEL_GPIO_15_MUX_SEL_VALUE_PORT_QSPI0_SD0 0x7
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_MUX_SEL_GPIO_15_MUX_SEL_VALUE_PORT_QSPI0_SD1 0x8
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_MUX_SEL_GPIO_15_MUX_SEL_VALUE_PORT_QSPI0_SD2 0x9
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_MUX_SEL_GPIO_15_MUX_SEL_VALUE_PORT_QSPI0_SD3 0xa
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_MUX_SEL_GPIO_15_MUX_SEL_VALUE_PORT_UART0_RX 0xb
#define CHIMERA_PADFRAME_AON_CONFIG_GPIO_15_MUX_SEL_GPIO_15_MUX_SEL_VALUE_PORT_UART0_TX 0xc

#ifdef __cplusplus
} // extern "C"
#endif
#endif // _CHIMERA_PADFRAME_AON_CONFIG_REG_DEFS_
       // End generated register defines for chimera_padframe_aon_config