// Generated register defines for snitch_cluster_peripheral

// Copyright information found in source file:
// Copyright 2020 ETH Zurich and University of Bologna.

// Licensing information found in source file:
// Licensed under Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51

#ifndef _SNITCH_CLUSTER_PERIPHERAL_REG_DEFS_
#define _SNITCH_CLUSTER_PERIPHERAL_REG_DEFS_

#ifdef __cplusplus
extern "C" {
#endif
// Number of performance counters
#define SNITCH_CLUSTER_PERIPHERAL_PARAM_NUM_PERF_COUNTERS 16

// Number of scratch registers
#define SNITCH_CLUSTER_PERIPHERAL_PARAM_NUM_CTRL_SCRATCH 4

// Register width
#define SNITCH_CLUSTER_PERIPHERAL_PARAM_REG_WIDTH 64

// Enable a particular performance counter to start tracking. (common
// parameters)
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_ENABLE_FIELD_WIDTH 1
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_ENABLE_FIELDS_PER_REG 64
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_MULTIREG_COUNT 16

// Enable a particular performance counter to start tracking.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_0_REG_OFFSET 0x0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_0_ENABLE_0_BIT 0

// Enable a particular performance counter to start tracking.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_1_REG_OFFSET 0x8
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_1_ENABLE_1_BIT 0

// Enable a particular performance counter to start tracking.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_2_REG_OFFSET 0x10
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_2_ENABLE_2_BIT 0

// Enable a particular performance counter to start tracking.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_3_REG_OFFSET 0x18
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_3_ENABLE_3_BIT 0

// Enable a particular performance counter to start tracking.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_4_REG_OFFSET 0x20
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_4_ENABLE_4_BIT 0

// Enable a particular performance counter to start tracking.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_5_REG_OFFSET 0x28
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_5_ENABLE_5_BIT 0

// Enable a particular performance counter to start tracking.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_6_REG_OFFSET 0x30
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_6_ENABLE_6_BIT 0

// Enable a particular performance counter to start tracking.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_7_REG_OFFSET 0x38
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_7_ENABLE_7_BIT 0

// Enable a particular performance counter to start tracking.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_8_REG_OFFSET 0x40
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_8_ENABLE_8_BIT 0

// Enable a particular performance counter to start tracking.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_9_REG_OFFSET 0x48
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_9_ENABLE_9_BIT 0

// Enable a particular performance counter to start tracking.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_10_REG_OFFSET 0x50
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_10_ENABLE_10_BIT 0

// Enable a particular performance counter to start tracking.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_11_REG_OFFSET 0x58
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_11_ENABLE_11_BIT 0

// Enable a particular performance counter to start tracking.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_12_REG_OFFSET 0x60
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_12_ENABLE_12_BIT 0

// Enable a particular performance counter to start tracking.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_13_REG_OFFSET 0x68
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_13_ENABLE_13_BIT 0

// Enable a particular performance counter to start tracking.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_14_REG_OFFSET 0x70
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_14_ENABLE_14_BIT 0

// Enable a particular performance counter to start tracking.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_15_REG_OFFSET 0x78
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_EN_15_ENABLE_15_BIT 0

// Select the metric that is tracked for each performance counter. (common
// parameters)
// Select the metric that is tracked for each performance counter.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_REG_OFFSET 0x80
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_HART_0_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_HART_0_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_HART_0_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_HART_0_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_HART_0_OFFSET })
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_OFFSET 16
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_OFFSET })
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_CYCLE 0x0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_TCDM_ACCESSED \
  0x1
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_TCDM_CONGESTED \
  0x2
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_ISSUE_FPU 0x3
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_ISSUE_FPU_SEQ \
  0x4
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_ISSUE_CORE_TO_FPU \
  0x5
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_RETIRED_INSTR \
  0x6
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_RETIRED_LOAD 0x7
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_RETIRED_I 0x8
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_RETIRED_ACC 0x9
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_DMA_AW_STALL 0xa
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_DMA_AR_STALL 0xb
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_DMA_R_STALL 0xc
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_DMA_W_STALL 0xd
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_DMA_BUF_W_STALL \
  0xe
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_DMA_BUF_R_STALL \
  0xf
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_DMA_AW_DONE 0x10
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_DMA_AW_BW 0x11
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_DMA_AR_DONE 0x12
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_DMA_AR_BW 0x13
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_DMA_R_DONE 0x14
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_DMA_R_BW 0x15
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_DMA_W_DONE 0x16
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_DMA_W_BW 0x17
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_DMA_B_DONE 0x18
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_DMA_BUSY 0x19
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_ICACHE_MISS 0x1a
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_ICACHE_HIT 0x1b
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_ICACHE_PREFETCH \
  0x1c
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_ICACHE_DOUBLE_HIT \
  0x1d
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_0_METRIC_0_VALUE_ICACHE_STALL \
  0x1e

// Select the metric that is tracked for each performance counter.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_1_REG_OFFSET 0x88
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_1_HART_1_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_1_HART_1_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_1_HART_1_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_1_HART_1_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_1_HART_1_OFFSET })
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_1_METRIC_1_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_1_METRIC_1_OFFSET 16
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_1_METRIC_1_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_1_METRIC_1_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_1_METRIC_1_OFFSET })

// Select the metric that is tracked for each performance counter.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_2_REG_OFFSET 0x90
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_2_HART_2_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_2_HART_2_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_2_HART_2_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_2_HART_2_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_2_HART_2_OFFSET })
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_2_METRIC_2_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_2_METRIC_2_OFFSET 16
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_2_METRIC_2_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_2_METRIC_2_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_2_METRIC_2_OFFSET })

// Select the metric that is tracked for each performance counter.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_3_REG_OFFSET 0x98
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_3_HART_3_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_3_HART_3_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_3_HART_3_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_3_HART_3_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_3_HART_3_OFFSET })
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_3_METRIC_3_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_3_METRIC_3_OFFSET 16
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_3_METRIC_3_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_3_METRIC_3_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_3_METRIC_3_OFFSET })

// Select the metric that is tracked for each performance counter.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_4_REG_OFFSET 0xa0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_4_HART_4_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_4_HART_4_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_4_HART_4_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_4_HART_4_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_4_HART_4_OFFSET })
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_4_METRIC_4_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_4_METRIC_4_OFFSET 16
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_4_METRIC_4_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_4_METRIC_4_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_4_METRIC_4_OFFSET })

// Select the metric that is tracked for each performance counter.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_5_REG_OFFSET 0xa8
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_5_HART_5_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_5_HART_5_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_5_HART_5_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_5_HART_5_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_5_HART_5_OFFSET })
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_5_METRIC_5_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_5_METRIC_5_OFFSET 16
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_5_METRIC_5_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_5_METRIC_5_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_5_METRIC_5_OFFSET })

// Select the metric that is tracked for each performance counter.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_6_REG_OFFSET 0xb0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_6_HART_6_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_6_HART_6_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_6_HART_6_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_6_HART_6_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_6_HART_6_OFFSET })
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_6_METRIC_6_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_6_METRIC_6_OFFSET 16
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_6_METRIC_6_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_6_METRIC_6_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_6_METRIC_6_OFFSET })

// Select the metric that is tracked for each performance counter.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_7_REG_OFFSET 0xb8
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_7_HART_7_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_7_HART_7_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_7_HART_7_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_7_HART_7_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_7_HART_7_OFFSET })
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_7_METRIC_7_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_7_METRIC_7_OFFSET 16
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_7_METRIC_7_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_7_METRIC_7_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_7_METRIC_7_OFFSET })

// Select the metric that is tracked for each performance counter.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_8_REG_OFFSET 0xc0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_8_HART_8_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_8_HART_8_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_8_HART_8_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_8_HART_8_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_8_HART_8_OFFSET })
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_8_METRIC_8_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_8_METRIC_8_OFFSET 16
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_8_METRIC_8_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_8_METRIC_8_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_8_METRIC_8_OFFSET })

// Select the metric that is tracked for each performance counter.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_9_REG_OFFSET 0xc8
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_9_HART_9_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_9_HART_9_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_9_HART_9_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_9_HART_9_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_9_HART_9_OFFSET })
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_9_METRIC_9_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_9_METRIC_9_OFFSET 16
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_9_METRIC_9_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_9_METRIC_9_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_9_METRIC_9_OFFSET })

// Select the metric that is tracked for each performance counter.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_10_REG_OFFSET 0xd0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_10_HART_10_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_10_HART_10_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_10_HART_10_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_10_HART_10_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_10_HART_10_OFFSET })
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_10_METRIC_10_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_10_METRIC_10_OFFSET 16
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_10_METRIC_10_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_10_METRIC_10_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_10_METRIC_10_OFFSET })

// Select the metric that is tracked for each performance counter.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_11_REG_OFFSET 0xd8
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_11_HART_11_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_11_HART_11_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_11_HART_11_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_11_HART_11_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_11_HART_11_OFFSET })
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_11_METRIC_11_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_11_METRIC_11_OFFSET 16
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_11_METRIC_11_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_11_METRIC_11_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_11_METRIC_11_OFFSET })

// Select the metric that is tracked for each performance counter.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_12_REG_OFFSET 0xe0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_12_HART_12_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_12_HART_12_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_12_HART_12_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_12_HART_12_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_12_HART_12_OFFSET })
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_12_METRIC_12_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_12_METRIC_12_OFFSET 16
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_12_METRIC_12_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_12_METRIC_12_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_12_METRIC_12_OFFSET })

// Select the metric that is tracked for each performance counter.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_13_REG_OFFSET 0xe8
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_13_HART_13_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_13_HART_13_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_13_HART_13_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_13_HART_13_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_13_HART_13_OFFSET })
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_13_METRIC_13_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_13_METRIC_13_OFFSET 16
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_13_METRIC_13_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_13_METRIC_13_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_13_METRIC_13_OFFSET })

// Select the metric that is tracked for each performance counter.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_14_REG_OFFSET 0xf0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_14_HART_14_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_14_HART_14_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_14_HART_14_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_14_HART_14_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_14_HART_14_OFFSET })
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_14_METRIC_14_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_14_METRIC_14_OFFSET 16
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_14_METRIC_14_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_14_METRIC_14_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_14_METRIC_14_OFFSET })

// Select the metric that is tracked for each performance counter.
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_15_REG_OFFSET 0xf8
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_15_HART_15_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_15_HART_15_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_15_HART_15_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_15_HART_15_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_15_HART_15_OFFSET })
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_15_METRIC_15_MASK 0xffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_15_METRIC_15_OFFSET 16
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_15_METRIC_15_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_15_METRIC_15_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_SEL_15_METRIC_15_OFFSET })

// Performance counter. Set corresponding PERF_CNT_SEL register depending on
// what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_PERF_COUNTER_FIELD_WIDTH 48
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_PERF_COUNTER_FIELDS_PER_REG 1
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_MULTIREG_COUNT 16

// Performance counter. Set corresponding PERF_CNT_SEL register depending on
// what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_0_REG_OFFSET 0x100
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_0_PERF_COUNTER_0_MASK 0xffffffffffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_0_PERF_COUNTER_0_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_0_PERF_COUNTER_0_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_0_PERF_COUNTER_0_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_0_PERF_COUNTER_0_OFFSET })

// Performance counter. Set corresponding PERF_CNT_SEL register depending on
// what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_1_REG_OFFSET 0x108
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_1_PERF_COUNTER_1_MASK 0xffffffffffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_1_PERF_COUNTER_1_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_1_PERF_COUNTER_1_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_1_PERF_COUNTER_1_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_1_PERF_COUNTER_1_OFFSET })

// Performance counter. Set corresponding PERF_CNT_SEL register depending on
// what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_2_REG_OFFSET 0x110
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_2_PERF_COUNTER_2_MASK 0xffffffffffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_2_PERF_COUNTER_2_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_2_PERF_COUNTER_2_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_2_PERF_COUNTER_2_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_2_PERF_COUNTER_2_OFFSET })

// Performance counter. Set corresponding PERF_CNT_SEL register depending on
// what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_3_REG_OFFSET 0x118
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_3_PERF_COUNTER_3_MASK 0xffffffffffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_3_PERF_COUNTER_3_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_3_PERF_COUNTER_3_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_3_PERF_COUNTER_3_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_3_PERF_COUNTER_3_OFFSET })

// Performance counter. Set corresponding PERF_CNT_SEL register depending on
// what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_4_REG_OFFSET 0x120
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_4_PERF_COUNTER_4_MASK 0xffffffffffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_4_PERF_COUNTER_4_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_4_PERF_COUNTER_4_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_4_PERF_COUNTER_4_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_4_PERF_COUNTER_4_OFFSET })

// Performance counter. Set corresponding PERF_CNT_SEL register depending on
// what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_5_REG_OFFSET 0x128
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_5_PERF_COUNTER_5_MASK 0xffffffffffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_5_PERF_COUNTER_5_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_5_PERF_COUNTER_5_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_5_PERF_COUNTER_5_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_5_PERF_COUNTER_5_OFFSET })

// Performance counter. Set corresponding PERF_CNT_SEL register depending on
// what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_6_REG_OFFSET 0x130
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_6_PERF_COUNTER_6_MASK 0xffffffffffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_6_PERF_COUNTER_6_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_6_PERF_COUNTER_6_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_6_PERF_COUNTER_6_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_6_PERF_COUNTER_6_OFFSET })

// Performance counter. Set corresponding PERF_CNT_SEL register depending on
// what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_7_REG_OFFSET 0x138
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_7_PERF_COUNTER_7_MASK 0xffffffffffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_7_PERF_COUNTER_7_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_7_PERF_COUNTER_7_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_7_PERF_COUNTER_7_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_7_PERF_COUNTER_7_OFFSET })

// Performance counter. Set corresponding PERF_CNT_SEL register depending on
// what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_8_REG_OFFSET 0x140
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_8_PERF_COUNTER_8_MASK 0xffffffffffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_8_PERF_COUNTER_8_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_8_PERF_COUNTER_8_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_8_PERF_COUNTER_8_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_8_PERF_COUNTER_8_OFFSET })

// Performance counter. Set corresponding PERF_CNT_SEL register depending on
// what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_9_REG_OFFSET 0x148
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_9_PERF_COUNTER_9_MASK 0xffffffffffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_9_PERF_COUNTER_9_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_9_PERF_COUNTER_9_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_9_PERF_COUNTER_9_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_9_PERF_COUNTER_9_OFFSET })

// Performance counter. Set corresponding PERF_CNT_SEL register depending on
// what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_10_REG_OFFSET 0x150
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_10_PERF_COUNTER_10_MASK \
  0xffffffffffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_10_PERF_COUNTER_10_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_10_PERF_COUNTER_10_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_10_PERF_COUNTER_10_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_10_PERF_COUNTER_10_OFFSET })

// Performance counter. Set corresponding PERF_CNT_SEL register depending on
// what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_11_REG_OFFSET 0x158
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_11_PERF_COUNTER_11_MASK \
  0xffffffffffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_11_PERF_COUNTER_11_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_11_PERF_COUNTER_11_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_11_PERF_COUNTER_11_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_11_PERF_COUNTER_11_OFFSET })

// Performance counter. Set corresponding PERF_CNT_SEL register depending on
// what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_12_REG_OFFSET 0x160
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_12_PERF_COUNTER_12_MASK \
  0xffffffffffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_12_PERF_COUNTER_12_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_12_PERF_COUNTER_12_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_12_PERF_COUNTER_12_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_12_PERF_COUNTER_12_OFFSET })

// Performance counter. Set corresponding PERF_CNT_SEL register depending on
// what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_13_REG_OFFSET 0x168
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_13_PERF_COUNTER_13_MASK \
  0xffffffffffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_13_PERF_COUNTER_13_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_13_PERF_COUNTER_13_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_13_PERF_COUNTER_13_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_13_PERF_COUNTER_13_OFFSET })

// Performance counter. Set corresponding PERF_CNT_SEL register depending on
// what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_14_REG_OFFSET 0x170
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_14_PERF_COUNTER_14_MASK \
  0xffffffffffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_14_PERF_COUNTER_14_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_14_PERF_COUNTER_14_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_14_PERF_COUNTER_14_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_14_PERF_COUNTER_14_OFFSET })

// Performance counter. Set corresponding PERF_CNT_SEL register depending on
// what
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_15_REG_OFFSET 0x178
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_15_PERF_COUNTER_15_MASK \
  0xffffffffffff
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_15_PERF_COUNTER_15_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_15_PERF_COUNTER_15_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_15_PERF_COUNTER_15_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_PERF_CNT_15_PERF_COUNTER_15_OFFSET })

// Scratch registers. Used in the bootrom for various purposes. (common
// parameters)
#define SNITCH_CLUSTER_PERIPHERAL_SCRATCH_SCRATCH_FIELD_WIDTH 32
#define SNITCH_CLUSTER_PERIPHERAL_SCRATCH_SCRATCH_FIELDS_PER_REG 2
#define SNITCH_CLUSTER_PERIPHERAL_SCRATCH_MULTIREG_COUNT 4

// Scratch registers. Used in the bootrom for various purposes.
#define SNITCH_CLUSTER_PERIPHERAL_SCRATCH_0_REG_OFFSET 0x180
#define SNITCH_CLUSTER_PERIPHERAL_SCRATCH_0_SCRATCH_0_MASK 0xffffffff
#define SNITCH_CLUSTER_PERIPHERAL_SCRATCH_0_SCRATCH_0_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_SCRATCH_0_SCRATCH_0_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_SCRATCH_0_SCRATCH_0_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_SCRATCH_0_SCRATCH_0_OFFSET })

// Scratch registers. Used in the bootrom for various purposes.
#define SNITCH_CLUSTER_PERIPHERAL_SCRATCH_1_REG_OFFSET 0x188
#define SNITCH_CLUSTER_PERIPHERAL_SCRATCH_1_SCRATCH_1_MASK 0xffffffff
#define SNITCH_CLUSTER_PERIPHERAL_SCRATCH_1_SCRATCH_1_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_SCRATCH_1_SCRATCH_1_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_SCRATCH_1_SCRATCH_1_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_SCRATCH_1_SCRATCH_1_OFFSET })

// Scratch registers. Used in the bootrom for various purposes.
#define SNITCH_CLUSTER_PERIPHERAL_SCRATCH_2_REG_OFFSET 0x190
#define SNITCH_CLUSTER_PERIPHERAL_SCRATCH_2_SCRATCH_2_MASK 0xffffffff
#define SNITCH_CLUSTER_PERIPHERAL_SCRATCH_2_SCRATCH_2_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_SCRATCH_2_SCRATCH_2_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_SCRATCH_2_SCRATCH_2_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_SCRATCH_2_SCRATCH_2_OFFSET })

// Scratch registers. Used in the bootrom for various purposes.
#define SNITCH_CLUSTER_PERIPHERAL_SCRATCH_3_REG_OFFSET 0x198
#define SNITCH_CLUSTER_PERIPHERAL_SCRATCH_3_SCRATCH_3_MASK 0xffffffff
#define SNITCH_CLUSTER_PERIPHERAL_SCRATCH_3_SCRATCH_3_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_SCRATCH_3_SCRATCH_3_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_SCRATCH_3_SCRATCH_3_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_SCRATCH_3_SCRATCH_3_OFFSET })

// Set bits in the cluster-local CLINT. Writing a 1 at location i sets the
// cluster-local interrupt
#define SNITCH_CLUSTER_PERIPHERAL_CL_CLINT_SET_REG_OFFSET 0x1a0
#define SNITCH_CLUSTER_PERIPHERAL_CL_CLINT_SET_CL_CLINT_SET_MASK 0xffffffff
#define SNITCH_CLUSTER_PERIPHERAL_CL_CLINT_SET_CL_CLINT_SET_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_CL_CLINT_SET_CL_CLINT_SET_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_CL_CLINT_SET_CL_CLINT_SET_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_CL_CLINT_SET_CL_CLINT_SET_OFFSET })

// Clear bits in the cluster-local CLINT. Writing a 1 at location i clears
// the cluster-local interrupt
#define SNITCH_CLUSTER_PERIPHERAL_CL_CLINT_CLEAR_REG_OFFSET 0x1a8
#define SNITCH_CLUSTER_PERIPHERAL_CL_CLINT_CLEAR_CL_CLINT_CLEAR_MASK 0xffffffff
#define SNITCH_CLUSTER_PERIPHERAL_CL_CLINT_CLEAR_CL_CLINT_CLEAR_OFFSET 0
#define SNITCH_CLUSTER_PERIPHERAL_CL_CLINT_CLEAR_CL_CLINT_CLEAR_FIELD \
  ((bitfield_field32_t) { .mask = SNITCH_CLUSTER_PERIPHERAL_CL_CLINT_CLEAR_CL_CLINT_CLEAR_MASK, .index = SNITCH_CLUSTER_PERIPHERAL_CL_CLINT_CLEAR_CL_CLINT_CLEAR_OFFSET })

// Controls prefetching of the instruction cache.
#define SNITCH_CLUSTER_PERIPHERAL_ICACHE_PREFETCH_ENABLE_REG_OFFSET 0x1b0
#define SNITCH_CLUSTER_PERIPHERAL_ICACHE_PREFETCH_ENABLE_ICACHE_PREFETCH_ENABLE_BIT \
  0

#ifdef __cplusplus
}  // extern "C"
#endif
#endif  // _SNITCH_CLUSTER_PERIPHERAL_REG_DEFS_
// End generated register defines for snitch_cluster_peripheral