
// SPDX-FileCopyrightText: 2025 ETH Zurich and University of Bologna
// SPDX-License-Identifier: Apache-2.0

#ifndef _ITA_DIMS_INCLUDE_GUARD_
#define _ITA_DIMS_INCLUDE_GUARD_

#define HEADS 1
#define SEQUENCE_LENGTH 256
#define EMBEDDING_SPACE 384
#define PROJECTION_SPACE 64
#define N_TILE_SEQUENCE_LENGTH 4
#define N_TILE_EMBEDDING_SPACE 6
#define N_TILE_PROJECTION_SPACE 1
#define TILE_SIZE_SEQUENCE_LENGTH 64
#define TILE_SIZE_EMBEDDING_SPACE 64
#define TILE_SIZE_PROJECTION_SPACE 64
#define N_CONTEXT 4

// 4x MatMul SxExP + 2xMatMul SxSxP + 4x Requant SxE
// + 1x Requant SxS + 1x Requant SxP + 1x Softmax SxS
#define SHA_OPS \
    (2ULL * 4ULL * SEQUENCE_LENGTH * EMBEDDING_SPACE * PROJECTION_SPACE + \
     2ULL * 2ULL * SEQUENCE_LENGTH * SEQUENCE_LENGTH * PROJECTION_SPACE + \
     4ULL * 4ULL * SEQUENCE_LENGTH * EMBEDDING_SPACE + 4ULL * SEQUENCE_LENGTH * SEQUENCE_LENGTH + \
     4ULL * SEQUENCE_LENGTH * PROJECTION_SPACE + 3ULL * SEQUENCE_LENGTH * SEQUENCE_LENGTH + \
     SEQUENCE_LENGTH)

#define MAX_TILE_SIZE \
    (MAX(TILE_SIZE_SEQUENCE_LENGTH, MAX(TILE_SIZE_PROJECTION_SPACE, TILE_SIZE_EMBEDDING_SPACE)))
#define MAX_BUFFER_SIZE (MAX_TILE_SIZE * MAX_TILE_SIZE)
#define MAX_BUFFER_BIAS_SIZE (3 * MAX_TILE_SIZE)

#endif //_ITA_DIMS_INCLUDE_GUARD_