# SPDX-FileCopyrightText: 2024 ETH Zurich and University of Bologna
# SPDX-License-Identifier: Apache-2.0
#
# Build-time helper functions for the Chimera multi-binary SDK.
#
# This file is invoked at BUILD time (after ELF files exist) via:
#   cmake -D CHIMERA_MODE=<mode> [-D VAR=VALUE ...] \
#         -P cmake/scripts/ChimeraBuildHelpers.cmake
#
# Available modes (select with -D CHIMERA_MODE=...):
#
#   symbols   - Extract public symbols from a device ELF, write a RISC-V
#               assembler stub and a matching C header.
#               Required variables: NM  ELF  TARGET_NAME  OUT_ASM  OUT_H
#
#   placement - Read __device_end from a device ELF, write a linker header
#               (.ldh) that exposes the 4 KiB-aligned end address so the
#               next binary in the placement chain can start there.
#               Required variables: NM  ELF  TARGET_NAME  OUT_LDH

# ---------------------------------------------------------------------------
# _chimera_run_nm(<elf> <flags> <output_var>)
#
# Internal macro: run llvm-nm on <elf> with <flags> and store stdout in
# <output_var>.  Aborts with FATAL_ERROR on non-zero exit code.
# ---------------------------------------------------------------------------
macro(_chimera_run_nm _ELF _FLAGS _OUTPUT_VAR)
    execute_process(
        COMMAND ${NM} ${_FLAGS} ${_ELF}
        OUTPUT_VARIABLE ${_OUTPUT_VAR}
        RESULT_VARIABLE _nm_exit
        ERROR_QUIET
    )
    if(NOT _nm_exit EQUAL 0)
        message(FATAL_ERROR
            "[CHIMERA] llvm-nm failed (exit ${_nm_exit}) on ${_ELF}\n"
            "Ensure the ELF has been built and NM points to a valid llvm-nm binary.")
    endif()
endmacro()

# ---------------------------------------------------------------------------
# chimera_generate_symbols()
#
# Reads all public defined symbols from a device ELF and writes two files:
#
#   OUT_ASM   RISC-V assembly file containing one `.set PSYM, 0xADDR` pair
#             per exported symbol.  Each symbol is prefixed with
#             TARGET_NAME_ so multiple device ELFs can coexist in the
#             host's link without name collisions.
#
#   OUT_H     C/C++ header with matching `extern char PSYM[];` declarations
#             guarded by an include-once macro derived from TARGET_NAME.
#
# Filtering rules:
#   - Only TEXT (T/t), DATA (D/d), BSS (B/b), and RODATA (R/r) symbols are
#     exported.  Undefined, weak, and ABS symbols are skipped.
#   - Symbols whose name starts with __ (double underscore) are skipped;
#     these are linker-internal (e.g. __bss_start, __device_end).
#
# Required cmake variables (pass with -D on the command line):
#   NM          Path to llvm-nm binary
#   ELF         Path to the built device ELF
#   TARGET_NAME Device target name; used as the symbol prefix
#   OUT_ASM     Output path for the generated assembler file (.s)
#   OUT_H       Output path for the generated C header (.h)
#   DEVICE_NAME Device name; used as the symbol prefix in the generated assembly (.s)
# ---------------------------------------------------------------------------
function(chimera_generate_symbols)
    _chimera_run_nm("${ELF}" "--defined-only;--extern-only;-n" NM_OUTPUT)

    string(REPLACE "\n" ";" NM_LINES "${NM_OUTPUT}")

    set(ASM_SYMS "")
    set(H_DECLS  "")

    foreach(line IN LISTS NM_LINES)
        if(NOT line)
            continue()
        endif()

        # nm output: <addr> <type> <name>
        if(NOT line MATCHES "^([0-9a-fA-F]+)[ \t]+([TtDdBbRr])[ \t]+(.+)$")
            continue()
        endif()

        set(ADDR "${CMAKE_MATCH_1}")
        set(SYM  "${CMAKE_MATCH_3}")
        string(STRIP "${SYM}" SYM)

        # Skip linker-internal symbols (double-underscore prefix)
        if(SYM MATCHES "^__")
            continue()
        endif()

        set(PSYM "${DEVICE_NAME}_${SYM}")
        string(APPEND ASM_SYMS ".global ${PSYM}\n")
        string(APPEND ASM_SYMS ".set    ${PSYM}, 0x${ADDR}\n")
        string(APPEND H_DECLS  "extern char ${PSYM}[]; /* 0x${ADDR} */\n")
    endforeach()

    file(WRITE "${OUT_ASM}"
        "/* Auto-generated device symbols for ${TARGET_NAME} - do not edit */\n"
        "/* Generated by cmake/scripts/ChimeraBuildHelpers.cmake (mode: symbols)   */\n"
        "\n"
        "${ASM_SYMS}"
    )

    string(TOUPPER "${TARGET_NAME}" GUARD)
    file(WRITE "${OUT_H}"
        "/* Auto-generated header for ${TARGET_NAME} device symbols - do not edit */\n"
        "/* Generated by cmake/scripts/ChimeraBuildHelpers.cmake (mode: symbols)          */\n"
        "\n"
        "#ifndef ${GUARD}_SYMBOLS_H\n"
        "#define ${GUARD}_SYMBOLS_H\n"
        "\n"
        "#ifdef __cplusplus\n"
        "extern \"C\" {\n"
        "#endif\n"
        "\n"
        "${H_DECLS}"
        "\n"
        "#ifdef __cplusplus\n"
        "}\n"
        "#endif\n"
        "\n"
        "#endif /* ${GUARD}_SYMBOLS_H */\n"
    )
endfunction()

# ---------------------------------------------------------------------------
# chimera_generate_placement()
#
# Reads the special __device_end symbol from a device ELF (via llvm-nm) and
# writes a linker header (.ldh) file that exposes the 4 KiB-aligned end
# address of the device binary to the next binary in the placement chain.
#
# The generated file contains one linker symbol:
#
#   __<TARGET_NAME>_end = <addr>;
#
# The next device's linker script INCLUDEs this file and uses the symbol
# to reserve the already-occupied memory region, preventing overlaps.
#
# Prerequisite: the device linker script must define
#   __device_end = ALIGN(0x1000);
# at the end of its SECTIONS block.
#
# Required cmake variables (pass with -D on the command line):
#   NM          Path to llvm-nm binary
#   ELF         Path to the built device ELF
#   TARGET_NAME Device target name (used as the symbol prefix)
#   OUT_LDH     Output path for the generated linker header (.ldh)
# ---------------------------------------------------------------------------
function(chimera_generate_placement)
    _chimera_run_nm("${ELF}" "--defined-only" NM_OUTPUT)

    string(REPLACE "\n" ";" NM_LINES "${NM_OUTPUT}")

    set(DEVICE_END "")
    foreach(line IN LISTS NM_LINES)
        if(line MATCHES "^([0-9a-fA-F]+)[ \t]+[A-Za-z][ \t]+__device_end$")
            set(DEVICE_END "0x${CMAKE_MATCH_1}")
            break()
        endif()
    endforeach()

    if(NOT DEVICE_END)
        message(FATAL_ERROR
            "[CHIMERA] Symbol '__device_end' not found in ${ELF}.\n"
            "The device linker script must define:\n"
            "  __device_end = ALIGN(0x1000);\n"
            "at the end of its SECTIONS block.")
    endif()

    file(WRITE "${OUT_LDH}"
        "/* Auto-generated placement for ${TARGET_NAME} - do not edit     */\n"
        "/* Generated by cmake/scripts/ChimeraBuildHelpers.cmake (mode: placement) */\n"
        "\n"
        "/* 4 KiB-aligned end of the ${TARGET_NAME} binary (code + data + stack). */\n"
        "/* The next binary's linker script INCLUDEs this file and uses            */\n"
        "/* __${TARGET_NAME}_end to skip over this device's memory region.         */\n"
        "__${TARGET_NAME}_end = ${DEVICE_END};\n"
    )
endfunction()

# ---------------------------------------------------------------------------
# Dispatcher: invoke the function selected by CHIMERA_MODE
# ---------------------------------------------------------------------------
if(CHIMERA_MODE STREQUAL "symbols")
    chimera_generate_symbols()
elseif(CHIMERA_MODE STREQUAL "placement")
    chimera_generate_placement()
else()
    message(FATAL_ERROR
        "[CHIMERA] Unknown CHIMERA_MODE '${CHIMERA_MODE}'.\n"
        "Valid modes: symbols, placement")
endif()
