// Generated register defines for chimerapd

// Copyright information found in source file:
// Copyright 2024 ETH Zurich and University of Bologna.

// Licensing information found in source file:
//
// SPDX-License-Identifier: SHL-0.51

#ifndef _CHIMERAPD_REG_DEFS_
#define _CHIMERAPD_REG_DEFS_

#ifdef __cplusplus
extern "C" {
#endif
// Register width
#define CHIMERAPD_PARAM_REG_WIDTH 32

// Set hyperbus PADs driving strength
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_REG_OFFSET 0x0
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_CS0_MASK 0x3
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_CS0_OFFSET 0
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_CS0_FIELD \
    ((bitfield_field32_t){.mask = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_CS0_MASK, \
                          .index = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_CS0_OFFSET})
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_CS1_MASK 0x3
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_CS1_OFFSET 2
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_CS1_FIELD \
    ((bitfield_field32_t){.mask = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_CS1_MASK, \
                          .index = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_CS1_OFFSET})
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_CLK_MASK 0x3
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_CLK_OFFSET 4
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_CLK_FIELD \
    ((bitfield_field32_t){.mask = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_CLK_MASK, \
                          .index = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_CLK_OFFSET})
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_CLKN_MASK 0x3
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_CLKN_OFFSET 6
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_CLKN_FIELD \
    ((bitfield_field32_t){.mask = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_CLKN_MASK, \
                          .index = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_CLKN_OFFSET})
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_RST_MASK 0x3
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_RST_OFFSET 8
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_RST_FIELD \
    ((bitfield_field32_t){.mask = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_RST_MASK, \
                          .index = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_RST_OFFSET})
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_RWDS_MASK 0x3
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_RWDS_OFFSET 10
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_RWDS_FIELD \
    ((bitfield_field32_t){.mask = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_RWDS_MASK, \
                          .index = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_RWDS_OFFSET})
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ0_MASK 0x3
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ0_OFFSET 12
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ0_FIELD \
    ((bitfield_field32_t){.mask = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ0_MASK, \
                          .index = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ0_OFFSET})
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ1_MASK 0x3
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ1_OFFSET 14
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ1_FIELD \
    ((bitfield_field32_t){.mask = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ1_MASK, \
                          .index = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ1_OFFSET})
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ2_MASK 0x3
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ2_OFFSET 16
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ2_FIELD \
    ((bitfield_field32_t){.mask = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ2_MASK, \
                          .index = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ2_OFFSET})
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ3_MASK 0x3
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ3_OFFSET 18
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ3_FIELD \
    ((bitfield_field32_t){.mask = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ3_MASK, \
                          .index = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ3_OFFSET})
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ4_MASK 0x3
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ4_OFFSET 20
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ4_FIELD \
    ((bitfield_field32_t){.mask = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ4_MASK, \
                          .index = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ4_OFFSET})
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ5_MASK 0x3
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ5_OFFSET 22
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ5_FIELD \
    ((bitfield_field32_t){.mask = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ5_MASK, \
                          .index = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ5_OFFSET})
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ6_MASK 0x3
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ6_OFFSET 24
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ6_FIELD \
    ((bitfield_field32_t){.mask = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ6_MASK, \
                          .index = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ6_OFFSET})
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ7_MASK 0x3
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ7_OFFSET 26
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ7_FIELD \
    ((bitfield_field32_t){.mask = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ7_MASK, \
                          .index = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_DQ7_OFFSET})
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_RESERVED_MASK 0xf
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_RESERVED_OFFSET 28
#define CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_RESERVED_FIELD \
    ((bitfield_field32_t){.mask = CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_RESERVED_MASK, \
                          .index = \
                              CHIMERAPD_HYPERBUS_PADS_DRV_STRENGTH_HYPERBUS_DRV_RESERVED_OFFSET})

#ifdef __cplusplus
} // extern "C"
#endif
#endif // _CHIMERAPD_REG_DEFS_
       // End generated register defines for chimerapd