# Copyright 2025 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Author: Victor Jung <jungvi@iis.ee.ethz.ch>

stages: # List of stages for jobs with their order of execution
  - build
  - test

.setup:
  script:
    - bash 
    - eval "$(micromamba shell hook --shell bash)"
    - micromamba activate chimera-sdk-ci
    - export CMAKE='/usr/sepp/bin/cmake-3.18.1'
    - export LLVM_INSTALL_PATH='/usr/pack/riscv-1.0-kgf/pulp-llvm-0.12.0'
    - export GVSOC_HOME='/scratch/jungvi/chimera-sdk/simulator_install/gvsoc'

build_sdk:
  stage: build
  parallel:
    matrix:
      - TARGET: [chimera-open, chimera-host, chimera-convolve]
  script:
    - !reference [.setup, script]
    - $CMAKE -DTARGET_PLATFORM=$TARGET -DTOOLCHAIN_DIR=$LLVM_INSTALL_PATH -B build
    - $CMAKE --build build -j

test:
  stage: test
  parallel:
    matrix:
      - TARGET: [chimera-open, chimera-host, chimera-convolve]
        TEST: [test_host_returnZero, test_snitchCluster_simpleOffload]
  script:
    - !reference [.setup, script]
    - $CMAKE -DTARGET_PLATFORM=$TARGET -DTOOLCHAIN_DIR=$LLVM_INSTALL_PATH -B build
    - $CMAKE --build build -j
    - cd ${GVSOC_HOME}
    - ./install/bin/gvsoc --target=chimera --binary $CI_PROJECT_DIR/build/$TEST hello image run