# Copyright 2025 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Author: Victor Jung <jungvi@iis.ee.ethz.ch>

variables:
  CMAKE: 'riscv /usr/sepp/bin/cmake-3.28.3'
  LLVM_INSTALL_PATH: '/usr/scratch/normandie/jungvi/llvm'
  GVSOC_HOME: '/scratch/jungvi/chimera-sdk/install/gvsoc'

stages: # List of stages for jobs with their order of execution
  - build
  - test

.setup:
  script:
    - bash
    - eval "$(micromamba shell hook --shell bash)"
    - micromamba activate chimera-sdk-ci
    - rm -rf build

build_sdk:
  stage: build
  parallel:
    matrix:
      - TARGET: [chimera-open, chimera-host, chimera-convolve]
  script:
    - !reference [.setup, script]
    - $CMAKE -DTARGET_PLATFORM=$TARGET -DTOOLCHAIN_DIR=$LLVM_INSTALL_PATH -B build
    - $CMAKE --build build -j

test:
  stage: test
  parallel:
    matrix:
      - TARGET: [chimera-open]
        TEST: [test_host_returnZero, test_snitchCluster_simpleOffload]
      - TARGET: [chimera-host]
        TEST: [test_host_returnZero]
  script:
    - !reference [.setup, script]
    - $CMAKE -DTARGET_PLATFORM=$TARGET -DTOOLCHAIN_DIR=$LLVM_INSTALL_PATH -B build
    - $CMAKE --build build -j
    - cd ${GVSOC_HOME}
    - ./install/bin/gvsoc --target=chimera --binary $CI_PROJECT_DIR/build/bin/$TEST run