// Generated register defines for cheshire

// Copyright information found in source file:
// Copyright 2020 ETH Zurich and University of Bologna.

// Licensing information found in source file:
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

/**
 * @defgroup targets_chimera_host Chimera-Host Target
 * @brief Target-specific definitions and interfaces for Chimera-Host.
 * @{
 */

/**
 * @defgroup targets_chimera_host_clint_registers CLINT Registers
 * @ingroup targets_chimera_host
 * @brief Register definitions for the CLINT (Core-Local Interruptor) in Chimera-Host.
 *
 * This header provides register definitions for the CLINT peripheral, which
 * handles inter-core software interrupts and timer interrupts.
 *
 * @note This file is automatically generated and should not be modified manually.
 *
 * @{
 *
 * @file clint.h
 * @date 2025-01-31
 */

#ifndef _CLINT_REG_DEFS_
#define _CLINT_REG_DEFS_

#ifdef __cplusplus
extern "C" {
#endif

/** @brief Number of cores in the system. */
#define CLINT_PARAM_NUM_CORES 1

/** @brief Register width in bits. */
#define CLINT_PARAM_REG_WIDTH 32

/** @name Machine Software Interrupt Pending (MSIP) Registers
 *  @brief Registers related to software interrupts.
 *  @{
 */
#define CLINT_MSIP_REG_OFFSET \
    0x0                      /**< Offset for Machine Software Interrupt Pending (MSIP) register. */
#define CLINT_MSIP_P_0_BIT 0 /**< Bit position of the MSIP interrupt pending flag. */

#define CLINT_MSIP_RSVD_0_MASK 0x7fffffff /**< Reserved mask for MSIP. */
#define CLINT_MSIP_RSVD_0_OFFSET 1        /**< Offset for reserved MSIP bits. */
#define CLINT_MSIP_RSVD_0_FIELD \
    ((bitfield_field32_t){.mask = CLINT_MSIP_RSVD_0_MASK, .index = CLINT_MSIP_RSVD_0_OFFSET})
/** @} */

/** @name Machine Timer Compare Registers
 *  @brief Registers that control machine timer compare values.
 *  @{
 */
#define CLINT_MTIMECMP_LOW0_REG_OFFSET \
    0x4000 /**< Offset for Machine Timer Compare Low register. \
            */
#define CLINT_MTIMECMP_HIGH0_REG_OFFSET \
    0x4004 /**< Offset for Machine Timer Compare High register. */
/** @} */

/** @name Machine Timer Registers
 *  @brief CLINT timer registers for maintaining system time.
 *  @{
 */
#define CLINT_MTIME_LOW_REG_OFFSET 0xbff8  /**< Offset for Machine Timer Low register. */
#define CLINT_MTIME_HIGH_REG_OFFSET 0xbffc /**< Offset for Machine Timer High register. */
/** @} */

#ifdef __cplusplus
} // extern "C"
#endif

#endif // _CLINT_REG_DEFS_

/** @} */ // End of targets_chimera_host_clint_registers group
/** @} */ // End of targets_chimera_host group
