// Copyright 2024 ETH Zurich and University of Bologna.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Philip Wiese <wiesep@iis.ee.ethz.ch>

#ifndef _CLUSTER_4_ADDR_MAP_INCLUDE_GUARD_
#define _CLUSTER_4_ADDR_MAP_INCLUDE_GUARD_

#include "addr_maps/soc_addr_map.h"

#include <stdint.h>

#define CLUSTER_4_TCDM_BASE_ADDR (CLUSTER_4_BASE)
#define CLUSTER_4_PERIPH_BASE_ADDR (CLUSTER_4_BASE + 0x20000)
#define CLUSTER_4_ZERO_MEM_BASE_ADDR (CLUSTER_4_BASE + 0x30000)
#define CLUSTER_4_HWPE_ITA_BASE_ADDR (CLUSTER_4_BASE + 0x40000)

// Define start and end of the regions
#define CLUSTER_4_TCDM_START_ADDR CLUSTER_4_TCDM_BASE_ADDR
#define CLUSTER_4_TCDM_END_ADDR CLUSTER_4_PERIPH_BASE_ADDR
#define CLUSTER_4_PERIPH_START_ADDR CLUSTER_4_PERIPH_BASE_ADDR
#define CLUSTER_4_PERIPH_END_ADDR CLUSTER_4_ZERO_MEM_BASE_ADDR
#define CLUSTER_4_ZERO_MEM_START_ADDR CLUSTER_4_ZERO_MEM_BASE_ADDR
#define CLUSTER_4_ZERO_MEM_END_ADDR CLUSTER_4_HWPE_ITA_BASE_ADDR
#define CLUSTER_4_HWPE_ITA_START_ADDR CLUSTER_4_HWPE_ITA_BASE_ADDR
#define CLUSTER_4_HWPE_ITA_END_ADDR (CLUSTER_4_BASE + 0x10000)

#define CLUSTER_4_HW_BARRIER_ADDR \
    (CLUSTER_4_PERIPH_BASE_ADDR + CLUSTER_4_PERIPHERAL_HW_BARRIER_REG_OFFSET)

#define CLUSTER_4_PERF_COUNTER_ADDR \
    (CLUSTER_4_PERIPH_BASE_ADDR + CLUSTER_4_PERIPHERAL_PERF_COUNTER_ENABLE_0_REG_OFFSET)

#define CLUSTER_4_HWPE_EVT_ADDR \
    (CLUSTER_4_PERIPH_BASE_ADDR + CLUSTER_4_PERIPHERAL_HWPE_EVT_REG_OFFSET)

#define CLUSTER_4_HWPE_BUSY_ADDR \
    (CLUSTER_4_PERIPH_BASE_ADDR + CLUSTER_4_PERIPHERAL_HWPE_BUSY_REG_OFFSET)

#endif //_CLUSTER_4_ADDR_MAP_INCLUDE_GUARD_