// Copyright 2024 ETH Zurich and University of Bologna.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Sergio Mazzola <smazzola@iis.ee.ethz.ch>

#ifndef _PULP_CLUSTER_ADDR_MAP_INCLUDE_GUARD_
#define _PULP_CLUSTER_ADDR_MAP_INCLUDE_GUARD_

#include <stdint.h>

#define PERIPH_OFFSET            0x00200000

#define FETCH_EN_OFFSET          (PERIPH_OFFSET + 0x008)

#define BOOT_ADDR_CORE_0_OFFSET  (PERIPH_OFFSET + 0x040)
#define BOOT_ADDR_CORE_1_OFFSET  (PERIPH_OFFSET + 0x044)
#define BOOT_ADDR_CORE_2_OFFSET  (PERIPH_OFFSET + 0x048)
#define BOOT_ADDR_CORE_3_OFFSET  (PERIPH_OFFSET + 0x04C)
#define BOOT_ADDR_CORE_4_OFFSET  (PERIPH_OFFSET + 0x050)
#define BOOT_ADDR_CORE_5_OFFSET  (PERIPH_OFFSET + 0x054)
#define BOOT_ADDR_CORE_6_OFFSET  (PERIPH_OFFSET + 0x058)
#define BOOT_ADDR_CORE_7_OFFSET  (PERIPH_OFFSET + 0x05C)
#define BOOT_ADDR_CORE_8_OFFSET  (PERIPH_OFFSET + 0x060)
#define BOOT_ADDR_CORE_9_OFFSET  (PERIPH_OFFSET + 0x064)
#define BOOT_ADDR_CORE_10_OFFSET (PERIPH_OFFSET + 0x068)
#define BOOT_ADDR_CORE_11_OFFSET (PERIPH_OFFSET + 0x06C)
#define BOOT_ADDR_CORE_12_OFFSET (PERIPH_OFFSET + 0x070)
#define BOOT_ADDR_CORE_13_OFFSET (PERIPH_OFFSET + 0x074)
#define BOOT_ADDR_CORE_14_OFFSET (PERIPH_OFFSET + 0x078)
#define BOOT_ADDR_CORE_15_OFFSET (PERIPH_OFFSET + 0x07C)

#endif